quarkus:
  datasource:
    db-kind: mysql
    username: user_user
    password: user_pswd
    jdbc:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&serverTimezone=Europe/Paris
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true