version: "3.8"
services:
  db_User:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_User
      - MYSQL_DATABASE=user
      - MYSQL_USER=user_user
      - MYSQL_PASSWORD=user_pswd
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p root_User' ]
      interval: 25s
      timeout: 10s
      retries: 5
  user:
    image: quarkus/user-jvm:latest
    depends_on:
      db_User:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: on-failure