version: "3.8"
services:
  commentdb:
    image: mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=comment
      - MYSQL_USER=comment_user
      - MYSQL_PASSWORD=comment_pswd
      - MYSQL_TCP_PORT= 3307
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p root' ]
      interval: 15s
      timeout: 10s
      retries: 5
  commentservice:
     image: quarkus/comment-jvm:latest
     depends_on:
      commentdb:
        condition: service_healthy
     ports:
      - "8081:8081"
     restart: on-failure