quarkus:
  http:
    port: 8081
  datasource:
    db-kind: mysql
    username: comment_user
    password: comment_pswd
    jdbc:
      url: jdbc:mysql://commentdb:3309/comment?useUnicode=true&serverTimezone=Europe/Paris
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
  swagger-ui:
    always-include: true
    path: /swagger-ui-Comment

"%test":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:mysql://localhost:3309/comment?useUnicode=true&serverTimezone=Europe/Paris
