name: Comments service Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd api/comments && ./mvnw package -DskipTests=true && docker build -f src/main/docker/Dockerfile.jvm -t quarkus/comments-jvm .
